/*
 * generated by dbLinter CLI
 */
package grisselbav.com.demo.validator;

import ch.islandsql.grammar.IslandSqlDialect;
import ch.islandsql.grammar.IslandSqlDocument;
import ch.islandsql.grammar.util.ParseTreeUtil;
import com.grisselbav.dblinter.validator.base.ValidatorUtil;
import com.grisselbav.dblinter.validator.model.CheckIssue;
import org.antlr.v4.runtime.tree.ErrorNode;
import org.junit.jupiter.api.Assertions;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

import java.io.IOException;
import java.util.List;
import java.util.Properties;

/**
 * Abstract base class for dbLinter validator test cases.
 */
public abstract class AbstractTest {
    protected IslandSqlDocument doc;
    protected List<CheckIssue> issues;

    protected static SingleConnectionDataSource dataSource;
    protected static JdbcTemplate jdbcTemplate;

    // Set up the database connection for checks that require a database connection.
    static {
        final Properties p = new Properties();
        try {
            p.load(AbstractTest.class.getClassLoader().getResourceAsStream("application.properties"));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        // User for read-only dictionary access
        String driverClassName = p.getProperty("jdbc.driverClassName");
        String url = p.getProperty("jdbc.url");
        String username = p.getProperty("jdbc.username");
        String password = p.getProperty("jdbc.password");
        if (driverClassName != null && !driverClassName.trim().isEmpty()
            && url != null && !url.trim().isEmpty()
            && username != null && !username.trim().isEmpty()
            && password != null && !password.trim().isEmpty())
        {
            // We have all JDBC properties to establish a connection
            dataSource = new SingleConnectionDataSource();
            dataSource.setDriverClassName(driverClassName);
            dataSource.setUrl(p.getProperty("jdbc.url"));
            dataSource.setUsername(p.getProperty("jdbc.username"));
            dataSource.setPassword(p.getProperty("jdbc.password"));
            jdbcTemplate = new JdbcTemplate(dataSource);
        } else {
            // We need all JDBC properties to establish a connection
            // As a result, when properties are missing, we do not provide a jdbcTemplate
            dataSource = null;
            jdbcTemplate = null;
        }
    }

    /**
     * Parse the SQL and optionally check for errors.
     *
     * @param builder the Island SQL document builder
     * @param assertErrors if true, assert that there are no errors in the parsed document
     */
    public void parse(IslandSqlDocument.Builder builder, boolean assertErrors) {
        doc = builder.build();
        if (assertErrors) {
            Assertions.assertFalse(doc.getFile().children.isEmpty());
            List<ErrorNode> errors = ParseTreeUtil.getAllContentsOfType(doc.getFile(), ErrorNode.class);
            Assertions.assertEquals(0, errors.size());
            Assertions.assertEquals(0, doc.getSyntaxErrors().size());
        }
    }

    /**
     * Parse the SQL and check for errors.
     *
     * @param builder the Island SQL document builder
     */
    public void parse(IslandSqlDocument.Builder builder) {
        parse(builder, true);
    }

    /**
     * Parse the SQL and optionally check for errors, hide out-of-scope tokens, and use the specified SQL dialect.
     *
     * @param sql the SQL to parse
     * @param assertErrors if true, assert that there are no errors in the parsed document
     * @param hideOutOfScopeTokens if true, hide tokens that are not part of the statements supported by IslandSQL
     * @param dialect the SQL dialect to use for parsing
     */
    public void parse(String sql, boolean assertErrors, boolean hideOutOfScopeTokens, IslandSqlDialect dialect) {
        parse(new IslandSqlDocument.Builder()
                .sql(sql)
                .hideOutOfScopeTokens(hideOutOfScopeTokens)
                .dialect(dialect),
            assertErrors);
    }

    /**
     * Parse the SQL and optionally check for errors and hide out-of-scope tokens.
     *
     * @param sql the SQL to parse
     * @param assertErrors if true, assert that there are no errors in the parsed document
     * @param hideOutOfScopeTokens if true, hide tokens that are not part of the statements supported by IslandSQL
     */
    public void parse(String sql, boolean assertErrors, boolean hideOutOfScopeTokens) {
        parse(new IslandSqlDocument.Builder()
                .sql(sql)
                .hideOutOfScopeTokens(hideOutOfScopeTokens),
            assertErrors);
    }

    /**
     * Parse the SQL and optionally check for errors.
     *
     * @param sql the SQL to parse
     * @param assertErrors if true, assert that there are no errors in the parsed document
     */
    public void parse(String sql, boolean assertErrors) {
        parse(new IslandSqlDocument.Builder().sql(sql), assertErrors);
    }

    /**
     * Parse the SQL and check for errors.
     *
     * @param sql the SQL to parse
     */
    public void parse(String sql) {
        parse(new IslandSqlDocument.Builder().sql(sql), true);
    }

    /**
     * Check the IslandSQL document for violations of the specified rule.
     *
     * @param tenant the tenant name for which to check the rule
     * @param rule the rule to check
     */
    public void check(String tenant, String rule) {
        issues = ValidatorUtil.check(tenant, rule, doc).getCheckIssues();
    }
}
