/*
 * generated by dbLinter CLI
 */
package grisselbav.com.demo.validator;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

import java.io.IOException;
import java.util.Properties;

/**
 * Abstract JDBC base class for dbLinter validator test cases.
 */
public abstract class AbstractJdbcTest {
    protected static SingleConnectionDataSource dataSource;
    protected static JdbcTemplate jdbcTemplate;

    // Set up the database connection for checks that require a database connection.
    static {
        final Properties p = new Properties();
        try {
            p.load(AbstractJdbcTest.class.getClassLoader().getResourceAsStream("application.properties"));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        // User for read-only dictionary access
        String driverClassName = p.getProperty("jdbc.driverClassName");
        String url = p.getProperty("jdbc.url");
        String username = p.getProperty("jdbc.username");
        String password = p.getProperty("jdbc.password");
        if (driverClassName != null && !driverClassName.trim().isEmpty()
            && url != null && !url.trim().isEmpty()
            && username != null && !username.trim().isEmpty()
            && password != null && !password.trim().isEmpty())
        {
            // We have all JDBC properties to establish a connection
            dataSource = new SingleConnectionDataSource();
            dataSource.setDriverClassName(driverClassName);
            dataSource.setUrl(p.getProperty("jdbc.url"));
            dataSource.setUsername(p.getProperty("jdbc.username"));
            dataSource.setPassword(p.getProperty("jdbc.password"));
            jdbcTemplate = new JdbcTemplate(dataSource);
        } else {
            // We need all JDBC properties to establish a connection
            // As a result, when properties are missing, we do not provide a jdbcTemplate
            dataSource = null;
            jdbcTemplate = null;
        }
    }
}
