/*
 * generated by dbLinter CLI
 */
package grisselbav.com.demo.validator;

import com.grisselbav.dblinter.validator.base.ValidatorUtil;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * Tests for Demo R-0770: Never allow application pages within an HTML frame.
 */
public class DemoR0770Test extends AbstractApxTest {
    @Nested
    public class APEX {
        @Test
        public void non_compliant_1() {
            parse("""
                    app DEMO (
                        security {
                            embedInFrames: allow
                        }
                    )
                    """);
            check("Demo", "R-0770");
            Assertions.assertEquals(1, issues.size());
            // issue 1
            var issue1 = issues.get(0);
            Assertions.assertEquals("""
                    Displaying content in frames is insecure.""", issue1.getMessage());
            Assertions.assertEquals(3, issue1.getRange().getStartLine());
            Assertions.assertEquals(24, issue1.getRange().getStartCol());
            Assertions.assertEquals(3, issue1.getRange().getEndLine());
            Assertions.assertEquals(29, issue1.getRange().getEndCol());
            Assertions.assertEquals(1, issue1.getQuickFixes().size());
            Assertions.assertEquals("Change value to allowSameOrigin.", issue1.getQuickFixes().get(0).getName());
            var expected1 = """
            app DEMO (
                security {
                    embedInFrames: allowSameOrigin
                }
            )
            """;
            String actual1 = ValidatorUtil.replace(doc.getTokenStream().getText(), issue1.getQuickFixes().get(0).get().get(0));
            Assertions.assertEquals(expected1, actual1);
        }

        @Nested
        public class Solution {
            @Test
            public void with_4_stars() {
                parse("""
                        app demo (
                            security {
                                embedInFrames: allowSameOrigin
                            }
                        )
                        """);
                check("Demo", "R-0770");
                Assertions.assertEquals(0, issues.size());
            }

            @Test
            public void with_5_stars() {
                parse("""
                        app demo (
                            security {
                                embedInFrames: deny
                            }
                        )
                        """);
                check("Demo", "R-0770");
                Assertions.assertEquals(0, issues.size());
            }

            @Test
            public void solution_5_star_after_export() {
                parse("""
                        app demo (
                            name: Demo App
                        )
                        """);
                check("Demo", "R-1010");
                Assertions.assertEquals(0, issues.size());
            }
        }
    }
}
