/*
 * generated by dbLinter CLI
 */
package grisselbav.com.demo.validator;

import com.grisselbav.dblinter.validator.model.CheckConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

/**
 * Tests for Demo R-4310: Never use GOTO statements in your code.
 */
public class DemoR4310Test extends AbstractTest {
    @Nested
    public class OracleDB {

        @Test
        public void non_compliant_1() {
            parse("""
                    create or replace package body my_package is
                       procedure password_check(in_password in varchar2) is
                          co_password    constant dba_users.password%type := in_password;
                          co_digitarray  constant varchar2(10 char)       := '0123456789';
                          co_lower_bound constant simple_integer          := 1;
                          co_errno       constant simple_integer          := -20501;
                          co_errmsg      constant varchar2(100 char)      := 'Password must contain a digit.';
                          l_isdigit      boolean                          := false;
                          l_len_pw       pls_integer;
                          l_len_array    pls_integer;
                       begin
                          l_len_pw    := length(co_password);
                          l_len_array := length(co_digitarray);
                    
                          <<check_digit>>
                          for i in co_lower_bound..l_len_array
                          loop
                             <<check_pw_char>>
                             for j in co_lower_bound..l_len_pw
                             loop
                                if substr(co_password,j,1) = substr(co_digitarray,i,1) then
                                   l_isdigit := true;
                                   goto check_other_things;
                                end if;
                             end loop check_pw_char;
                          end loop check_digit;
                    
                          <<check_other_things>>
                          null;
                    
                          if not l_isdigit then
                             raise_application_error(co_errno,co_errmsg);
                          end if;
                       end password_check;
                    end my_package;
                    /
                    """);
            check("Demo", "R-4310");
            Assertions.assertEquals(1, issues.size());
            // issue 1
            var issue1 = issues.get(0);
            Assertions.assertEquals("""
                    Using GOTO.""", issue1.getMessage());
            Assertions.assertEquals(23, issue1.getRange().getStartLine());
            Assertions.assertEquals(16, issue1.getRange().getStartCol());
            Assertions.assertEquals(23, issue1.getRange().getEndLine());
            Assertions.assertEquals(20, issue1.getRange().getEndCol());
        }

        @Nested
        public class Solution {

            @Test
            public void with_3_stars() {
                parse("""
                        create or replace package body my_package is
                           procedure password_check(in_password in varchar2) is
                              co_password    constant dba_users.password%type := in_password;
                              co_digitarray  constant varchar2(10 char)       := '0123456789';
                              co_lower_bound constant simple_integer          := 1;
                              co_errno       constant simple_integer          := -20501;
                              co_errmsg      constant varchar2(100 char)      := 'Password must contain a digit.';
                              l_isdigit      boolean                          := false;
                              l_len_pw       pls_integer;
                              l_len_array    pls_integer;
                           begin
                              l_len_pw    := length(co_password);
                              l_len_array := length(co_digitarray);
                        
                              <<check_digit>>
                              for i in co_lower_bound..l_len_array
                              loop
                                 <<check_pw_char>>
                                 for j in co_lower_bound..l_len_pw
                                 loop
                                    if substr(co_password,j,1) = substr(co_digitarray,i,1) then
                                       l_isdigit := true;
                                    end if;
                                 end loop check_pw_char;
                              end loop check_digit;
                        
                              <<check_other_things>>
                              null;
                        
                              if not l_isdigit then
                                 raise_application_error(co_errno,co_errmsg);
                              end if;
                           end password_check;
                        end my_package;
                        /
                        """);
                check("Demo", "R-4310");
                Assertions.assertEquals(0, issues.size());
            }

            @Test
            public void with_5_stars() {
                parse("""
                        create or replace package body my_package is
                           procedure password_check(in_password in varchar2) is
                              co_password     constant dba_users.password%type := in_password;
                              co_digitpattern constant varchar2(10 char)       := '\\d';
                              co_errno        constant simple_integer          := -20501;
                              co_errmsg       constant varchar2(100 char)      := 'Password must contain a digit.';
                           begin
                              if not regexp_like(co_password,co_digitpattern) then
                                 raise_application_error(co_errno,co_errmsg);
                              end if;
                           end password_check;
                        end my_package;
                        /
                        """);
                check("Demo", "R-4310");
                Assertions.assertEquals(0, issues.size());
            }
        }
    }
}
