/*
 * generated by dbLinter CLI
 */
package grisselbav.com.demo.validator;

import com.grisselbav.dblinter.validator.model.CheckConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

/**
 * Tests for Demo R-2320: Never use VARCHAR data type.
 */
public class DemoR2320Test extends AbstractTest {
    @BeforeEach
    @AfterEach
    public void setup() {
        Map<String, String> params = new HashMap<>();
        CheckConfig.INSTANCE.setParameters(params);
        CheckConfig.INSTANCE.setJdbcTemplate(jdbcTemplate);
        // TODO: clear check cache if there is one
    }

    @Nested
    public class OracleDB {

        @Test
        public void non_compliant_1() {
            parse("""
                    create or replace package types_up is
                       subtype description_type is varchar(200);
                    end types_up;
                    /
                    """);
            check("Demo", "R-2320");
            Assertions.assertEquals(1, issues.size());
            // issue 1
            var issue1 = issues.get(0);
            Assertions.assertEquals("""
                    Use VARHCHAR2 instead of VARCHAR data type.""", issue1.getMessage());
            Assertions.assertEquals(2, issue1.getRange().getStartLine());
            Assertions.assertEquals(32, issue1.getRange().getStartCol());
            Assertions.assertEquals(2, issue1.getRange().getEndLine());
            Assertions.assertEquals(44, issue1.getRange().getEndCol());
            // TODO: assert quick fixes
        }

        @Nested
        public class Solution {

            @Test
            public void with_5_stars() {
                parse("""
                        create or replace package types_up is
                           subtype description_type is varchar2(200 char);
                        end types_up;
                        /
                        """);
                check("Demo", "R-2320");
                Assertions.assertEquals(0, issues.size());
            }
        }
    }
}
