/*
 * generated by dbLinter CLI
 */
package grisselbav.com.demo.validator;

import com.grisselbav.dblinter.validator.model.CheckConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

/**
 * Tests for Demo R-0770: Never allow application pages within an HTML frame.
 */
public class DemoR0770Test extends AbstractApxTest {
    @BeforeEach
    @AfterEach
    public void setup() {
        Map<String, String> params = new HashMap<>();
        params.put("ApexWorkspaces", """
                dblinter, dbl_gui""");
        CheckConfig.INSTANCE.setParameters(params);
        CheckConfig.INSTANCE.setJdbcTemplate(jdbcTemplate);
        // TODO: clear check cache if there is one
    }

    @Nested
    public class APEX {

        @Test
        public void non_compliant_1() {
            parse("""
                    app DEMO (
                        security {
                            embedInFrames: allow
                        }
                    )
                    """);
            check("Demo", "R-0770");
            Assertions.assertEquals(1, issues.size());
            // issue 1
            var issue1 = issues.get(0);
            Assertions.assertEquals("""
                    Displaying content in frames is insecure.""", issue1.getMessage());
            Assertions.assertEquals(3, issue1.getRange().getStartLine());
            Assertions.assertEquals(24, issue1.getRange().getStartCol());
            Assertions.assertEquals(3, issue1.getRange().getEndLine());
            Assertions.assertEquals(29, issue1.getRange().getEndCol());
            // TODO: assert quick fixes
        }

        @Nested
        public class Solution {

            @Test
            public void with_4_stars() {
                parse("""
                        app demo (
                            security {
                                embedInFrames: allowSameOrigin
                            }
                        )
                        """);
                check("Demo", "R-0770");
                Assertions.assertEquals(0, issues.size());
            }

            @Test
            public void with_5_stars() {
                parse("""
                        app demo (
                            security {
                                embedInFrames: deny
                            }
                        )
                        """);
                check("Demo", "R-0770");
                Assertions.assertEquals(0, issues.size());
            }
        }
    }
}
