/*
 * generated by dbLinter CLI
 */
package grisselbav.com.demo.validator;

import com.grisselbav.dblinter.validator.model.CheckConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

/**
 * Tests for Demo R-3194: Always specify INNER or OUTER within JOIN TO ONE.
 */
public class DemoR3194Test extends AbstractTest {
    @BeforeEach
    @AfterEach
    public void setup() {
        Map<String, String> params = new HashMap<>();
        CheckConfig.INSTANCE.setParameters(params);
        CheckConfig.INSTANCE.setJdbcTemplate(jdbcTemplate);
        // TODO: clear check cache if there is one
    }

    @Nested
    public class OracleDB {

        @Test
        public void non_compliant_1() {
            parse("""
                    select e.first_name || ' ' || e.last_name as employee_full_name
                          ,e.salary
                          ,d.department_name
                          ,j.job_title
                          ,mgr.first_name || ' ' || mgr.last_name as manager_full_name
                          ,mgr.salary as manager_salary
                      from employees e
                      join to one (
                              departments d
                             ,jobs j
                             ,employees mgr on e.manager_id = mgr.employee_id
                           )
                     where e.salary > mgr.salary
                        or mgr.employee_id is null;
                    """);
            check("Demo", "R-3194");
            Assertions.assertEquals(3, issues.size());
            // issue 1
            var issue1 = issues.get(0);
            Assertions.assertEquals("""
                    Specify an OUTER or INNER JOIN clause for departments.""", issue1.getMessage());
            Assertions.assertEquals(9, issue1.getRange().getStartLine());
            Assertions.assertEquals(11, issue1.getRange().getStartCol());
            Assertions.assertEquals(9, issue1.getRange().getEndLine());
            Assertions.assertEquals(22, issue1.getRange().getEndCol());
            // issue 2
            var issue2 = issues.get(1);
            Assertions.assertEquals("""
                    Specify an OUTER or INNER JOIN clause for jobs.""", issue2.getMessage());
            Assertions.assertEquals(10, issue2.getRange().getStartLine());
            Assertions.assertEquals(11, issue2.getRange().getStartCol());
            Assertions.assertEquals(10, issue2.getRange().getEndLine());
            Assertions.assertEquals(15, issue2.getRange().getEndCol());
            // issue 3
            var issue3 = issues.get(2);
            Assertions.assertEquals("""
                    Specify an OUTER or INNER JOIN clause for employees.""", issue3.getMessage());
            Assertions.assertEquals(11, issue3.getRange().getStartLine());
            Assertions.assertEquals(11, issue3.getRange().getStartCol());
            Assertions.assertEquals(11, issue3.getRange().getEndLine());
            Assertions.assertEquals(20, issue3.getRange().getEndCol());
            // TODO: assert quick fixes
        }

        @Nested
        public class Solution {

            @Test
            public void with_5_stars() {
                parse("""
                        select e.first_name || ' ' || e.last_name as employee_full_name
                              ,e.salary
                              ,d.department_name
                              ,j.job_title
                              ,mgr.first_name || ' ' || mgr.last_name as manager_full_name
                              ,mgr.salary as manager_salary
                          from employees e
                          join to one (
                                  inner join departments d
                                  inner join jobs j
                                  outer join employees mgr on e.manager_id = mgr.employee_id
                               )
                         where e.salary > mgr.salary
                            or mgr.employee_id is null;
                        """);
                check("Demo", "R-3194");
                Assertions.assertEquals(0, issues.size());
            }
        }
    }
}
