/*
 * generated by dbLinter CLI
 */
package com.grisselbav.demo.validator;

import ch.islandsql.grammar.IslandSqlParser;
import com.grisselbav.dblinter.validator.base.AbstractCheck;
import com.grisselbav.dblinter.validator.base.Check;
import com.grisselbav.dblinter.validator.model.CheckIssue;

import java.util.List;

/**
 * Demo R-4310: Never use GOTO statements in your code.
 */
public class DemoR4310 extends AbstractCheck {
    @Check(tenant = "Demo", rule = "R-4310")
    public List<CheckIssue> checkGotoStatement(IslandSqlParser.GotoStatementContext ctx) {
        addIssue()
                .setRange(ctx.start)
                .setMessage("Using GOTO.")
                .addDbLinterIgnoreQuickFix(ctx, "Using GOTO because ...");
        return checkIssues;
    }
}
