/*
 * generated by dbLinter CLI
 */
package com.grisselbav.demo.validator;

import ch.islandsql.grammar.util.ParseTreeUtil;
import com.grisselbav.apexlang.grammar.ApexLangDocument;
import com.grisselbav.dblinter.validator.base.ValidatorUtil;
import com.grisselbav.dblinter.validator.model.CheckIssue;
import org.antlr.v4.runtime.tree.ErrorNode;
import org.junit.jupiter.api.Assertions;

import java.util.List;

/**
 * Abstract base class for dbLinter validator test cases processing APEXlang source.
 */
public abstract class AbstractApxTest extends AbstractJdbcTest {
    protected ApexLangDocument doc;
    protected List<CheckIssue> issues;

    /**
     * Parse the APEXlang source and optionally check for errors.
     *
     * @param builder the APEXlang document builder
     * @param assertErrors if true, assert that there are no errors in the parsed document
     */
    public void parse(ApexLangDocument.Builder builder, boolean assertErrors) {
        doc = builder.build();
        if (assertErrors) {
            Assertions.assertFalse(doc.getApxFile().children.isEmpty());
            List<ErrorNode> errors = ParseTreeUtil.getAllContentsOfType(doc.getApxFile(), ErrorNode.class);
            Assertions.assertEquals(0, errors.size());
            Assertions.assertEquals(0, doc.getSyntaxErrors().size());
        }
    }

    /**
     * Parse the APEXlang source and check for errors.
     *
     * @param builder the APEXlang document builder
     */
    public void parse(ApexLangDocument.Builder builder) {
        parse(builder, true);
    }

    /**
     * Parse the APEXlang source and optionally check for errors.
     *
     * @param apexlang the APEXlang source to parse
     * @param assertErrors if true, assert that there are no errors in the parsed document
     */
    public void parse(String apexlang, boolean assertErrors) {
        parse(new ApexLangDocument.Builder().apexlang(apexlang), assertErrors);
    }

    /**
     * Parse the APEXlang source and check for errors.
     *
     * @param apexlang the APEXlang source to parse
     */
    public void parse(String apexlang) {
        parse(new ApexLangDocument.Builder().apexlang(apexlang), true);
    }

    /**
     * Check the APEXlang document for violations of the specified rule.
     *
     * @param tenant the tenant name for which to check the rule
     * @param rule the rule to check
     */
    public void check(String tenant, String rule) {
        issues = ValidatorUtil.check(tenant, rule, doc).getCheckIssues();
    }
}
