/*
 * generated by dbLinter CLI
 */
package com.grisselbav.demo.validator;

import com.grisselbav.dblinter.validator.base.ValidatorUtil;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * Tests for Demo R-2320: Never use VARCHAR data type.
 */
public class DemoR2320Test extends AbstractTest {
    @Nested
    public class OracleDB {

        @Test
        public void non_compliant_1() {
            parse("""
                    create or replace package types_up is
                       subtype description_type is varchar(200);
                    end types_up;
                    /
                    """);
            check("Demo", "R-2320");
            Assertions.assertEquals(1, issues.size());
            // issue 1
            var issue1 = issues.get(0);
            Assertions.assertEquals("""
                    Use VARCHAR2 instead of VARCHAR data type.""", issue1.getMessage());
            Assertions.assertEquals(2, issue1.getRange().getStartLine());
            Assertions.assertEquals(32, issue1.getRange().getStartCol());
            Assertions.assertEquals(2, issue1.getRange().getEndLine());
            Assertions.assertEquals(39, issue1.getRange().getEndCol());
            // quick fix 1
            var expected = """
                create or replace package types_up is
                   subtype description_type is varchar2(200);
                end types_up;
                /
                """;
            String actual = ValidatorUtil.applyReplacements(doc, issue1.getQuickFixes().get(0).get());
            Assertions.assertEquals(expected, actual);
        }

        @Nested
        public class Solution {

            @Test
            public void with_5_stars() {
                parse("""
                        create or replace package types_up is
                           subtype description_type is varchar2(200 char);
                        end types_up;
                        /
                        """);
                check("Demo", "R-2320");
                Assertions.assertEquals(0, issues.size());
            }
        }
    }
}
