/*
 * generated by dbLinter CLI
 */
package com.grisselbav.demo.validator;

import com.grisselbav.dblinter.validator.model.CheckConfig;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

/**
 * Tests for Demo R-5070: Avoid using Oracle predefined exceptions.
 */
public class DemoR5070Test extends AbstractTest {
    @BeforeEach
    @AfterEach
    public void setup() {
        Map<String, String> params = new HashMap<>();
        params.put("PredefinedExceptionNames", """
                access_into_null, case_not_found,collection_is_null, cursor_already_open, dup_val_on_index, invalid_cursor, invalid_number, login_denied, no_data_found, no_data_needed, not_logged_on, program_error, rowtype_mismatch, self_is_null, storage_error, subscript_beyond_count, subscript_outside_limit, sys_invalid_rowid, timeout_on_resource, too_many_rows, value_error, zero_divide""");
        CheckConfig.INSTANCE.setParameters(params);
        DemoR5070.clearCache();
    }

    @Nested
    public class OracleDB {

        @Test
        public void non_compliant_1() {
            parse("""
                    begin
                       raise no_data_found;
                    end;
                    /
                    """);
            check("Demo", "R-5070");
            Assertions.assertEquals(1, issues.size());
            // issue 1
            var issue1 = issues.get(0);
            Assertions.assertEquals("""
                    Raising Oracle predefined exception no_data_found.""", issue1.getMessage());
            Assertions.assertEquals(2, issue1.getRange().getStartLine());
            Assertions.assertEquals(10, issue1.getRange().getStartCol());
            Assertions.assertEquals(2, issue1.getRange().getEndLine());
            Assertions.assertEquals(23, issue1.getRange().getEndCol());
        }

        @Nested
        public class Solution {

            @Test
            public void with_5_stars() {
                parse("""
                        declare
                           e_my_exception exception;
                        begin
                           raise e_my_exception;
                        end;
                        /
                        """);
                check("Demo", "R-5070");
                Assertions.assertEquals(0, issues.size());
            }
        }
    }
}
