/*
 * generated by dbLinter CLI
 */
package com.grisselbav.demo.validator;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

/**
 * Tests for Demo R-3131: Never use ANSI SQL-92 join syntax.
 */
public class DemoR3131Test extends AbstractTest {
    @Nested
    public class OracleDB {

        @Test
        public void non_compliant_1() {
            parse("""
                    select emp.employee_id
                          ,emp.last_name
                          ,emp.first_name
                          ,dept.department_name
                      from employees emp
                      join departments dept
                        on dept.department_id = emp.department_id
                     where extract(month from emp.hire_date) = extract(month from sysdate);
                    """);
            check("Demo", "R-3131");
            Assertions.assertEquals(1, issues.size());
            // issue 1
            var issue1 = issues.get(0);
            Assertions.assertEquals("""
                    Use Oracle instead of ANSI SQL-92 join syntax.""", issue1.getMessage());
            Assertions.assertEquals(6, issue1.getRange().getStartLine());
            Assertions.assertEquals(3, issue1.getRange().getStartCol());
            Assertions.assertEquals(6, issue1.getRange().getEndLine());
            Assertions.assertEquals(7, issue1.getRange().getEndCol());
        }

        @Nested
        public class Solution {

            @Test
            public void with_5_stars() {
                parse("""
                        select e.employee_id
                              ,e.last_name
                              ,e.first_name
                              ,d.department_name
                          from employees e
                              ,departments d
                         where e.department_id = d.department_id
                           and extract(month from e.hire_date) = extract(month from sysdate);
                        """);
                check("Demo", "R-3131");
                Assertions.assertEquals(0, issues.size());
            }
        }
    }
}
