/*
 * generated by dbLinter CLI
 */
package grisselbav.com.demo.validator;

import ch.islandsql.grammar.IslandSqlParser;
import com.grisselbav.dblinter.validator.base.AbstractCheck;
import com.grisselbav.dblinter.validator.base.Check;
import com.grisselbav.dblinter.validator.model.CheckIssue;

import java.util.List;

/**
 * Demo R-9010: Always use a format model in string to date/time conversion functions.
 */
public class DemoR9010 extends AbstractCheck {
    @Check(tenant = "Demo", rule = "R-9010")
    public List<CheckIssue> checkPlsqlStatement(IslandSqlParser.FileContext ctx) {
        // TODO: Implement one or more checks with different, suitable IslandSqlParser contexts.
        return checkIssues;
    }
}
