/*
 * generated by dbLinter CLI
 */
package grisselbav.com.demo.validator;

import ch.islandsql.grammar.IslandSqlParser;
import com.grisselbav.dblinter.validator.base.AbstractCheck;
import com.grisselbav.dblinter.validator.base.Check;
import com.grisselbav.dblinter.validator.model.CheckIssue;

import java.util.List;

/**
 * Demo R-5070: Avoid using Oracle predefined exceptions.
 */
public class DemoR5070 extends AbstractCheck {
    @Check(tenant = "Demo", rule = "R-5070")
    public List<CheckIssue> checkPlsqlStatement(IslandSqlParser.FileContext ctx) {
        // TODO: Implement one or more checks with different, suitable IslandSqlParser contexts.
        return checkIssues;
    }
}
