/*
 * generated by dbLinter CLI
 */
package grisselbav.com.demo.validator;

import ch.islandsql.grammar.IslandSqlParser;
import com.grisselbav.dblinter.validator.base.AbstractCheck;
import com.grisselbav.dblinter.validator.base.Check;
import com.grisselbav.dblinter.validator.model.CheckIssue;

import java.util.List;

/**
 * Demo R-3131: Never use ANSI SQL-92 join syntax.
 */
public class DemoR3131 extends AbstractCheck {
    @Check(tenant = "Demo", rule = "R-3131")
    public List<CheckIssue> checkPlsqlStatement(IslandSqlParser.JoinVariantContext ctx) {
        addIssue()
                .setRange(ctx.start)
                .setMessage("Use Oracle instead of ANSI SQL-92 join syntax.");
        return checkIssues;
    }
}
